version: "3.8"
services:
  postgres-db:
    container_name: capstone-postgres
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: capstone
      POSTGRES_PASSWORD: capstone
      POSTGRES_DB: capstone_db
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5432:5432" # outside port, inside port

    volumes:
      - postgresql_data:/var/lib/postgresql/data/18
      # something is going on with docker, anythin 18+ wants an additional path after /data
      # if using an older version deleting the 18 should work

volumes:
  postgresql_data:
