version: "3.8"
services:
  postgres-db:
    container_name: capstone-postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: capstone
      POSTGRES_PASSWORD: capstone
      POSTGRES_DB: capstone_db
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5432:5432" # outside port, inside port

    volumes:
      - capstone_france_data:/var/lib/postgresql/data
      # something is going on with docker, anything 18+ wants an additional path after /data
      # I'm specifying that docker using version 17 for images

volumes:
  capstone_france_data:
